#!/bin/sh

### BEGIN INIT INFO
# Provides:             Rasprinter
# Required-Start:       $network $local_fs $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Rasprinter labels printer daemon
### END INIT INFO

case "${1}" in
	start)
		# Wait some times before starting the daemon to make sure the GPIO controller is ready (or this can trigger false prints)
		(sleep 5 && cd /opt/Rasprinter && ./Rasprinter) &
		;;

	stop)
		killall Rasprinter
		;;

	*)
		echo "Usage: ${0} {start|stop}" >&2
		exit 1
		;;
esac

exit 0
